name: Prevent dev branch auto-deletion

conditions:
  # Target only the dev branch
  ref:
    include:
      - refs/heads/dev
    exclude: []

rules:
  - !override
    type: deletion
    parameters:
      # Prevent deletion of the dev branch
      protected_branches:
        - dev
